literals
 : literal*
 ;
literal
 : NIL
 | BOOL
 | INT
 | STR
 | array
 | hash
 | range
 ;
array
 : '[' ( literal',' )* ']'
 ;
hash
 : '{' ( literal '=>' literal',' )* '}'
 ;
range
 : int_range
 | str_range
 ;
int_range
 : '('INT'..'INT')'
 | '('INT'...'INT')'
 ;
str_range
 : '('STR'..'STR')'
 | '('STR'...'STR')'
 ;